# Generated by Django 5.1.2 on 2024-10-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_watchlist_delete_savedstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='added_at',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='current_price',
            field=models.FloatField(default=0.0),
        ),
    ]
