# Generated by Django 5.1.2 on 2024-10-16 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_watchlist_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='current_price',
        ),
    ]
