# Generated by Django 5.1.2 on 2024-10-16 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_watchlist_current_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-id']},
        ),
    ]
