# Generated by Django 5.1.2 on 2024-10-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_watchlist_options_savedstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
